/**
 * The reader app's bundled copy of the campus seed (B09-02). GENERATED by
 * `node scripts/check-campus-seed.mjs --write` from
 * supabase/migrations/20261002140000_dw_campuses.sql; do not edit by hand.
 * Shown when the campus list cannot be fetched. The live list is the
 * dw_campuses table, kept by the owner in /staff -> Settings -> Campuses.
 */
import type { CampusRow } from './campuses';

export const FALLBACK_CAMPUSES: CampusRow[] = [
  {
    "id": "au-paradise",
    "name": "Futures Paradise",
    "city": "Paradise, SA",
    "region": "Australia",
    "congregation": "futures-au",
    "timeZone": "Australia/Adelaide",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 10
  },
  {
    "id": "au-adelaide-city",
    "name": "Futures Adelaide City",
    "city": "Adelaide, SA",
    "region": "Australia",
    "congregation": "futures-au",
    "timeZone": "Australia/Adelaide",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 20
  },
  {
    "id": "au-salisbury",
    "name": "Futures Salisbury",
    "city": "Salisbury, SA",
    "region": "Australia",
    "congregation": "futures-au",
    "timeZone": "Australia/Adelaide",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 30
  },
  {
    "id": "au-south",
    "name": "Futures South",
    "city": "South Australia",
    "region": "Australia",
    "congregation": "futures-au",
    "timeZone": "Australia/Adelaide",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 40
  },
  {
    "id": "au-clare-valley",
    "name": "Futures Clare Valley",
    "city": "Clare Valley, SA",
    "region": "Australia",
    "congregation": "futures-au",
    "timeZone": "Australia/Adelaide",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 50
  },
  {
    "id": "au-mount-barker",
    "name": "Futures Mount Barker",
    "city": "Mount Barker, SA",
    "region": "Australia",
    "congregation": "futures-au",
    "timeZone": "Australia/Adelaide",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 60
  },
  {
    "id": "au-victor-harbor",
    "name": "Futures Victor Harbor",
    "city": "Victor Harbor, SA",
    "region": "Australia",
    "congregation": "futures-au",
    "timeZone": "Australia/Adelaide",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 70
  },
  {
    "id": "au-copper-coast",
    "name": "Futures Copper Coast",
    "city": "Copper Coast, SA",
    "region": "Australia",
    "congregation": "futures-au",
    "timeZone": "Australia/Adelaide",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 80
  },
  {
    "id": "us-gwinnett",
    "name": "Futures Gwinnett",
    "city": "Gwinnett, GA",
    "region": "North America",
    "congregation": "futures-us",
    "timeZone": "America/New_York",
    "sundayUntil": "16:00",
    "videoUrl": "https://www.youtube.com/embed/live_stream?channel=UCbrXwvwaPr_ZootS3z8YKLQ",
    "sortOrder": 90
  },
  {
    "id": "us-kennesaw",
    "name": "Futures Kennesaw",
    "city": "Kennesaw, GA",
    "region": "North America",
    "congregation": "futures-us",
    "timeZone": "America/New_York",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 100
  },
  {
    "id": "us-alpharetta",
    "name": "Futures Alpharetta",
    "city": "Alpharetta, GA",
    "region": "North America",
    "congregation": "futures-us",
    "timeZone": "America/New_York",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 110
  },
  {
    "id": "us-futuros-duluth",
    "name": "Futuros Duluth",
    "city": "Duluth, GA",
    "region": "North America",
    "congregation": "futuros-us",
    "timeZone": "America/New_York",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 120
  },
  {
    "id": "us-futuros-kennesaw",
    "name": "Futuros Kennesaw",
    "city": "Kennesaw, GA",
    "region": "North America",
    "congregation": "futuros-us",
    "timeZone": "America/New_York",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 130
  },
  {
    "id": "us-futuros-grayson",
    "name": "Futuros Grayson",
    "city": "Grayson, GA",
    "region": "North America",
    "congregation": "futuros-us",
    "timeZone": "America/New_York",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 140
  },
  {
    "id": "us-franklin",
    "name": "Futures Franklin",
    "city": "Franklin, TN",
    "region": "North America",
    "congregation": "futures-us",
    "timeZone": "America/Chicago",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 150
  },
  {
    "id": "id-solo",
    "name": "Futures Solo",
    "city": "Surakarta, Central Java",
    "region": "Indonesia",
    "congregation": null,
    "timeZone": "Asia/Jakarta",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 160
  },
  {
    "id": "id-cemani",
    "name": "Futures Cemani",
    "city": "Cemani, Central Java",
    "region": "Indonesia",
    "congregation": null,
    "timeZone": "Asia/Jakarta",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 170
  },
  {
    "id": "id-bali",
    "name": "Futures Bali",
    "city": "Denpasar, Bali",
    "region": "Indonesia",
    "congregation": null,
    "timeZone": "Asia/Makassar",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 180
  },
  {
    "id": "id-samarinda",
    "name": "Futures Samarinda",
    "city": "Samarinda, East Kalimantan",
    "region": "Indonesia",
    "congregation": null,
    "timeZone": "Asia/Makassar",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 190
  },
  {
    "id": "id-langowan",
    "name": "Futures Langowan",
    "city": "Langowan, North Sulawesi",
    "region": "Indonesia",
    "congregation": null,
    "timeZone": "Asia/Makassar",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 200
  },
  {
    "id": "br-rio",
    "name": "Futures Rio",
    "city": "Rio de Janeiro, Brazil",
    "region": "Brazil",
    "congregation": null,
    "timeZone": "America/Sao_Paulo",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 210
  },
  {
    "id": "other",
    "name": "Non-Futures Church",
    "city": "Any",
    "region": "Other",
    "congregation": null,
    "timeZone": "UTC",
    "sundayUntil": "16:00",
    "videoUrl": null,
    "sortOrder": 220
  }
];
